vest_ifam/urls.py
from django.urls import path
from . import views

app_name = "vest_ifam"

urlpatterns = [
    path('', views.index, name="index"),
    path('quiz/', views.quiz, name="quiz"),
    path('start_quiz/', views.start_quiz, name="start_quiz"),
    path('questions_quiz/', views.questions_quiz, name="questions_quiz"),
    path('video_class/', views.video_class, name="video_class"),

]

website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('vest_ifam.urls'))
]

vest_ifam/models.py
from django.db import models

# Create your models here.

vest_ifam/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'vest_ifam/pages/index.html')

def quiz(request):
    return render(request, 'vest_ifam/pages/quiz.html')

def start_quiz(request):
    return render(request, 'vest_ifam/pages/start_quiz.html')

def questions_quiz(request):
    return render(request, 'vest_ifam/pages/questions_quiz.html')

def video_class(request):
    return render(request, 'vest_ifam/pages/video_class.html')

templates/vest_ifam/base.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    {% block extra_head %}
    {% endblock extra_head %}

    {% block extra_style %}
    {% endblock extra_style %}
</head>
<body>
{% block content %}

{% endblock content %}
{% block scripts %}

{% endblock scripts %}
</body>
</html>

templates/vest_ifam/pages/index.html
{% extends "vest_ifam/base.html" %}
{% load static %}

{% block title %}
VestIfam
{% endblock title %}


{% block extra_style %}
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

  <link rel="stylesheet" href=" {% static 'vest_ifam/css/index/styles.css'%}">
  <link rel="stylesheet" href=" {% static 'vest_ifam/css/index/styles2.css'%}">
  <link rel="stylesheet" href=" {% static 'vest_ifam/css/index/styles3.css'%}">
  <link rel="stylesheet" href=" {% static 'vest_ifam/css/index/styles4.css'%}">
  <link rel="stylesheet" href=" {% static 'vest_ifam/css/index/styles5.css'%}">
  <link rel="stylesheet" href=" {% static 'vest_ifam/css/index/styles6.css'%}">
  <link rel="stylesheet" href=" {% static 'vest_ifam/css/index/styles7.css'%}">
  <link rel="stylesheet" href=" {% static 'vest_ifam/css/index/styles8.css'%}">
{% endblock extra_style %}

{% block content %}  
<!-- Elemento da tela de login (modal) -->
<div id="modal" class="modal">
  <div class="modal-content">
    <span class="close-button" onclick="closeModal()">&times;</span>
    <h2>Faça Login ou Cadastro<br> no VestIFAM</h2> <!-- Adicionando a quebra de linha -->
    <form>
      <div class="form-group">
        <label for="username">Usuário:</label>
        <input type="text" id="username" name="username" placeholder="Digite seu usuário">
      </div>
      <div class="form-group">
        <label for="password">Senha:</label>
        <input type="password" id="password" name="password" placeholder="Digite sua senha">
      </div>
      <div class="buttons-login">
        <button type="submit">Login</button>
        <div id="buttonDiv"></div> <!-- Aqui será inserido o botão do Google -->
        <p>Ao se cadastrar você estará concordando com os <u>Termos de Uso</u> e <u>Política de Privacidade</u>.</p>
      </div>
      
    </form>
  </div>
</div>
  
  <header>
    <nav>
      <a href="index.html" class="logo-link">
        <div class="logo">
          <img src="{% static 'vest_ifam/images/index/24.png'%}" alt="">
        </div>
      </a>
  
      <!-- Ícone do menu para versão mobile -->
      <div class="mobile-menu-icon">
        <i class="fas fa-bars"></i>
      </div>
  
      <!-- Itens da barra de navegação -->
      <div class="nav-items">
        <div class="search-bar">
          <i class="fas fa-search"></i>
          <input type="text" id="search-input-header" placeholder="Pesquisar">
        </div>
  
        <a>
          <div class="login-button">
            <button id="button-login" type="button">Login</button>
          </div>
        </a>
      </div>
    </nav>
  </header>

  
  <!-- Sidebar para versão mobile -->
<div class="sidebar">
  <!-- Botão para fechar a sidebar -->
  <div class="close-button1">
    <i class="fas fa-times"></i>
  </div>

  <!-- Movendo a barra de pesquisa e botão de login para a sidebar -->
  <div class="search-bar">
    <i class="fas fa-search"></i>
    <input type="text" id="search-input-sidebar" placeholder="Pesquisar">
  </div>

  <a>
    <div class="login-button">
      <button id="button-login-sidebar" type="button">Login</button>
    </div>
  </a>
</div>

  <div id="conteudo">
  
 
    <div class="green-background">
        <p>Estude tudo e revise rápido.</p>
    </div>
    
      <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="true" style="overflow: hidden; height: 500px; width: 100%; margin-top: 50px;">
        <div class="carousel-indicators">
          <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
          <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
          <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
        </div>
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img src="{% static 'vest_ifam/images/index/PhotoReal_Alunos_estudando_em_uma_sala_de_aula_0.jpg" class="d-block w-100" alt="...">
          </div>
          <div class="carousel-item">
            <img src="{% static 'vest_ifam/images/index/16.png'%}" class="d-block w-100" alt="...">
          </div>
          <div class="carousel-item">
            <img src="{% static 'vest_ifam/images/index/19.png'%}" class="d-block w-100" alt="...">
          </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>
    
    
    <div class="container">
      <div class="center-images">
        <div class="image15">
          <img src="{% static 'vest_ifam/images/index/7.png'%}">
        </div>
        <div class="image16">
          <a href="pagina-materiais.html">
            <img src="{% static 'vest_ifam/images/index/16.png'%}">
            <p class="caption">Materiais</p>
            <p class="textoembaixo">Resumos, exercícios e<br>muito mais</p>
          </a>
        </div>
        <div class="image17">
          <a href="{% url "vest_ifam:video_class" %}">
            <img src="{% static 'vest_ifam/images/index/17.png'%}">
            <p class="caption">VideoAulas</p>
            <p class="textoembaixo">Link de aulas<br>completas de diversos temas</p>
          </a>
        </div>
        <div class="image18">
          <a href="{% url "vest_ifam:quiz" %}">
            <img src="{% static 'vest_ifam/images/index/18.png'%}">
            <p class="caption">Perguntas e Respostas</p>
            <p class="textoembaixo">Perguntas há cada<br>15 minutos de revisão</p>
          </a>
        </div>
        <div class="image19">
          <img src="{% static 'vest_ifam/images/index/8.png'%}">
        </div>
      </div>
    </div>


    <div class="text-container2">
      <p class="main-text">Estude com mais facilidade.</p>
      <div class="image-stack">
        <div class="image-container2">
          <a href="page1.html">
            <img src="{% static 'vest_ifam/images/index/21.png'%}" alt="Image 1">
            <div class="image-overlay">
              <p class="image-text">Vestibulares</p>
            </div>
          </a>
        </div>
        <div class="image-container2">
          <a href="page2.html">
            <img src="{% static 'vest_ifam/images/index/22.png'%}" alt="Image 2">
            <div class="image-overlay">
              <p class="image-text">Português</p>
            </div>
          </a>
        </div>
        <div class="image-container2">
          <a>
            <img src="{% static 'vest_ifam/images/index/23.png'%}" onclick="translateToEnglish()"   alt="Image 3" >
            <div class="image-overlay">
              <p class="image-text">Inglês</p>
            </div>
          </a>
      </div>
    </div>

    <div class="image-container3">
      <img src="{% static 'vest_ifam/images/index/24.png'%}" alt="Image 1">
      <img src="{% static 'vest_ifam/images/index/25.png'%}" alt="Image 2">
    </div>

    <footer>
      <div class="footer-left">
        <p><strong>Sobre Nós</strong></p>
        <div class="textoembaixofooter1">
          <p>Utilizem o nosso site<br>Estudantes de ensino médio</p>
        </div>
      </div>

      <div class="footer-center">
        <div class="social-media-icons">
          <a href="https://instagram.com/vestifam?igshid=MzNlNGNkZWQ4Mg==">
            <i class="fab fa-instagram"></i>
            <p>VestIFAM</p>
          </a>
        </div>
      </div>

        <div class="footer-right">
          <p><strong>Conteúdos</strong></p>
          <div class="textoembaixofooter1">
            <a href="materiais.html"><p>Materiais de estudo</p></a>
            <a href="C:\Users\Usuário\Desktop\Rayner\VestIfam\Versões\V5_VestIfam\QUIZ\quiz.html"><p>Perguntas</p></a>
            <a href="disciplinas.html"><p>Disciplinas</p></a>
            <a href="todos.html"><p>Todos os Conteúdos</p></a>
          </div>
        </div>  
    </footer>
    
    <div>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integridade="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://accounts.google.com/gsi/client" async></script>
    <script src="https://unpkg.com/jwt-decode/build/jwt-decode.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <!-- Inclua o jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>



    <script src="{% static 'vest_ifam/js/index/script.js' %}"></script>
    <script src="{% static 'vest_ifam/js/index/script2.js' %}"></script>
    <script src="{% static 'vest_ifam/js/index/script3.js' %}"></script>
    <script src="{% static 'vest_ifam/js/index/script4.js' %}"></script>
    <script src="{% static 'vest_ifam/js/index/script5.js' %}"></script>
    <script src="{% static 'vest_ifam/js/index/script6.js' %}"></script>
    <script src="{% static 'vest_ifam/js/index/script7.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/index/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
{% endblock content %}

templates/vest_ifam/pages/questions_quiz.html
{% extends "vest_ifam/base.html" %}
{% load static %}
{% block title %}QUIZ{% endblock title %}

{% block extra_style %}
<link rel="stylesheet" href="{% static 'vest_ifam/css/quiz/stylesQuizQuestions.css'%}">  
{% endblock extra_style %}
    
{% block content %}    
    <div class="Screendecision">
        <div class="Painel">
            <div class="Questions">
                <div class="quiz-container">
                    <button class="quiz-button" id="opcaoA"></button>
                    <button class="quiz-button" id="opcaoB"></button>
                    <button class="quiz-button" id="opcaoC"></button>
                    <button class="quiz-button" id="opcaoD"></button>
                    <button class="quiz-button" id="opcaoE"></button>
                </div>
            </div>

            <div class="Backquestion">
                <h1 id="numberQuestion"></h1>
                <img class="Imgquestion" src="{% static 'vest_ifam/images/quiz/imgQuestion.png' %}" />
                <h1 id="Txtquestion"></h1>
                <div id="relogio-segundos"></div>  
            </div>
        </div>
    </div>
    <div class="ResolutionContainer" style="display: none;">
        <div class="ResolutionMessage"></div>
        <img class="Imgquestion" src="{% static 'vest_ifam/images/quiz/imgQuestion.png' %}" />
    </div>
{% endblock content %}

{% block scripts %}
<script src="{% static 'vest_ifam/js/quiz/quizQuestion.js'%}"></script>
{% endblock scripts %}

templates/vest_ifam/pages/quiz.html
{% extends "vest_ifam/base.html" %}
{% load static %}

{% block title %}QUIZ{% endblock title %}
{% block extra_style %}
<link rel="stylesheet" href="{% static 'vest_ifam/css/quiz/stylesQUIZ.css'%}">
{% endblock extra_style %}

{% block content %}
    <div class="molduraTela" id="quizContainer">
        <div class="painel">
            <div class="logoVestIfam">
                <img src="{% static 'vest_ifam/images/quiz/logoVestIFAM.png' %}" alt="Logo VestIfam" class="logoVestIfam-img" />
            </div>
            <div class="txtHRQ">
                <img src="{% static 'vest_ifam/images/quiz/txtQUIZ.png' %}" alt="HoraDoQuiz" />
            </div>
            <div class="start">
                <a href="{% url "vest_ifam:start_quiz" %}" id="startBTN">Start</a>
            </div>      
            <div class="elementosQUIZ">
                <ul class="icon-list">
                    <li class="Icon Lamp1"><img src="{% static 'vest_ifam/images/quiz/lamp1.png' %}" alt="Lamp 1" /></li>
                    <li class="Icon Lamp2"><img src="{% static 'vest_ifam/images/quiz/lamp2.png' %}" alt="Lamp 2" /></li>
                    <li class="Icon Pencil1"><img src="{% static 'vest_ifam/images/quiz/pencil1.png' %}" alt="Pencil 1" /></li>
                    <li class="Icon Pencil2"><img src="{% static 'vest_ifam/images/quiz/pencil2.png' %}" alt="Pencil 2" /></li>
                    <li class="Icon Book1"><img src="{% static 'vest_ifam/images/quiz/book1.png' %}" alt="Book 1" /></li>
                    <li class="Icon Book2"><img src="{% static 'vest_ifam/images/quiz/book2.png' %}" alt="Book 2" /></li>
                </ul>
            </div>
        </div>
    </div>
{% endblock content %}

templates/vest_ifam/pages/start_quiz.html
{% extends "vest_ifam/base.html" %}
{% load static %}
{% block title %}QUIZ{% endblock title %}
{% block extra_style %}
<link rel="stylesheet" href="{% static 'vest_ifam/css/quiz/stylesQuizIntro.css' %}">
{% endblock extra_style %}

{% block content %}
    <div class="Screentutoras">
        <div class="Divprincipal">
            <img class="Backgroundintroducao" src="{% static 'vest_ifam/images/quiz/backgroundIntroducao.png' %}" alt="Background" />
            <div class="Btnstarttutora">
                <div class="Btnstarttutora-inner">
                    <a href="{% url 'vest_ifam:questions_quiz' %}" class="Iniciar">INICIAR</a>
                </div>
            </div>
            <div class="Logovestifam">
                <img class="Logovestifam-inner" src="{% static 'vest_ifam/images/quiz/logoVestIFAM.png' %}" alt="Logo" />
            </div>
            <div class="Txtintro2">
                <div class="Txtsubintro2">Não se esqueçam de conferir sua resposta antes de enviá-la, pois uma vez submetida, não poderá ser alterada.</div>
                <div class="Instructioncircle2"></div>
                <div class="NumberCircle">2</div>
            </div>
            <div class="Txtintro1">
                <div class="CadaPerguntaTerApenasUmaRespostaCorretaVocTerUmTempoLimitadoParaResponderEntOFiqueLigado">Cada pergunta terá apenas uma resposta correta, você terá um tempo limitado para responder, então fique ligado!</div>
                <div class="Instructioncircle1"></div>
                <div class="NumberCircle">1</div>
            </div>
            <div class="Txtmain">Bem-vindos a este empolgante quiz dos obtidos até aqui conhecimentos! Antes de começarmos, vamos às regras:</div>
            <div class="Txttitle">
                <span class="Txttitle-span1"></span>
                <span class="Txttitle-span2">TESTE SEUS<br/>CONHECIMENTOS</span>
            </div>
        </div>
    </div>
{% endblock content %}

templates/vest_ifam/pages/video_class.html
{% extends "vest_ifam/base.html" %}
{% load static %}

{% block title %}Video{% endblock title %}

{% block extra_head %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
{% endblock extra_head %}

{% block extra_style %}
<link rel="stylesheet" href="{% static 'vest_ifam/css/video/stylesVideoAulas.css">
{% endblock extra_style %}

{% block content %}
    <nav class="navbar navbar-expand-lg" style="background-color: #7ED957;">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">
                <img src="{% static 'vest_ifam/images/video/LogoVestIFAM.png' %}" alt="Logo" width="55" height="45" class="d-inline-block align-text-top">
                <img src="{% static 'vest_ifam/images/video/LogoVestIFAMTXT.png' %}" alt="Logo" width="90" height="me-auto" class="d-inline-block align-text-top">
              </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                
            </ul>
            <span class="navbar-text">
              Espaço Login do cara
            </span>
          </div>
        </div>
      </nav>

      <div class="SegundoElemento" style="border-bottom: #D9D9D9 solid 2px; margin-top: 30px  ;">
        <p class="h2 ms-4" >Todos os Videos</p>
      </div>

     <div class="container text-center" style="margin-top: 50px;">

        <div class="row" style="margin-bottom: 30px;">

          <div class="col align-self-start">
                        <div class="card" style="width: 12rem;">
              <img src="{% static 'vest_ifam/images/video/6.png' %}" class="card-img-top" alt="...">
              <div class="card-body">
                <a href="https://youtu.be/BbG-zFs0WZ0?si=d0b4amdPiiFNfmIH" class="btn btn-primary" style="background-color: #BCBEFA; border: none; color: black;" >Acessar</a>
              </div>
            </div>
          </div>
          <div class="col align-self-start">
                        <div class="card" style="width: 12rem;">
              <img src="{% static 'vest_ifam/images/video/5.png' %}" class="card-img-top" alt="...">
              <div class="card-body">
                <a href="https://youtu.be/4ZJnTqTk4_Y?si=kjICqQsqcQIYtLkj" class="btn btn-primary" style="background-color: #BCBEFA; border: none; color: black">Acessar</a>
              </div>
            </div>
          </div>

          <div class="col align-self-start">
                        <div class="card" style="width: 12rem;">
              <img src="{% static 'vest_ifam/images/video/4.png' %}" class="card-img-top" alt="...">
              <div class="card-body">
                <a href="https://youtu.be/Sy_LUnePfRE?si=PbLvN3lz5bLsSSlr" class="btn btn-primary" style="background-color: #BCBEFA; border: none; color: black">Acessar</a>
              </div>
            </div>
          </div>
          <div class="col align-self-start">
                        <div class="card" style="width: 12rem;">
              <img src="{% static 'vest_ifam/images/video/3.png' %}" class="card-img-top" alt="...">
              <div class="card-body">
                <a href="https://youtu.be/bLg5Ug8SBYw?si=CY87J1-rz89G2pib" class="btn btn-primary" style="background-color: #BCBEFA; border: none; color: black">Acessar</a>
              </div>
            </div>
          </div>
          
          <div class="col align-self-end">
                        <div class="card" style="width: 12rem;">
              <img src="{% static 'vest_ifam/images/video/8.png' %}" class="card-img-top" alt="...">
              <div class="card-body">
                <a href="https://youtu.be/c4yBSJzIqmg?si=60ftRffaJbMS_GxT" class="btn btn-primary" style="background-color: #BCBEFA; border: none; color: black">Acessar</a>
              </div>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col align-self-start">
                        <div class="card" style="width: 12rem;">
              <img src="{% static 'vest_ifam/images/video/7.png' %}" class="card-img-top" alt="...">
              <div class="card-body">
                <a href="https://youtu.be/NbZnXcBw12Y?si=IBAp2260VHfuKcol" class="btn btn-primary" style="background-color: #BCBEFA; border: none; color: black">Acessar</a>
              </div>
            </div>
          </div>
          <div class="col align-self-start">
                        <div class="card" style="width: 12rem;">
              <img src="{% static 'vest_ifam/images/video/9.png' %}" class="card-img-top" alt="...">
              <div class="card-body">
                <a href="https://youtu.be/BbG-zFs0WZ0?si=d0b4amdPiiFNfmIH" class="btn btn-primary" style="background-color: #BCBEFA; border: none; color: black">Acessar</a>
              </div>
            </div>
          </div>
          <div class="col align-self-start">
                        <div class="card" style="width: 12rem;">
              <img src="{% static 'vest_ifam/images/video/10.png' %}" class="card-img-top" alt="...">
              <div class="card-body">
                <a href="https://youtu.be/JLb__tey3AM?si=hCiQ36gNj6L6SUiA" class="btn btn-primary" style="background-color: #BCBEFA; border: none; color: black">Acessar</a>
              </div>
            </div>
          </div>
          <div class="col align-self-center">
                        <div class="card" style="width: 12rem;">
              <img src="{% static 'vest_ifam/images/video/1.png' %}" class="card-img-top" alt="...">
              <div class="card-body">
                <a href="https://youtu.be/xfjSzZf6JA4?si=H-aNFAYFkBVhVqQ5" class="btn btn-primary" style="background-color: #BCBEFA; border: none; color: black">Acessar</a>
              </div>
            </div>
          </div>

          
          
          <div class="col align-self-end">
                        <div class="card" style="width: 12rem;">
              <img src="{% static 'vest_ifam/images/video/2.png' %}" class="card-img-top" alt="...">
              <div class="card-body">
                <a href="https://youtu.be/SdBMj-zEx-A?si=zKlmcSV9TDyNHJYJ" class="btn btn-primary" style="background-color: #BCBEFA; border: none; color: black">Acessar</a>
              </div>
            </div>
          </div>
        </div>
      </div>
{% endblock content %}

{% block scripts %}
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
{% endblock scripts %}